name: conecta_mayor
description: "Aplicación de tutoriales y cursos básicos para adultos mayores"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/conecta.png

  fonts:
    - family: Century Gothic
      fonts:
        - asset: assets/fonts/centurygothic.ttf
          weight: 400
        - asset: assets/fonts/centurygothic_bold.ttf
          weight: 700

# Configuración para el icono de la aplicación
flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/conecta.png"
  remove_alpha_ios: true # Elimina transparencia en iOS (para evitar círculo)
  min_sdk_android: 21
